ALTER TABLE pickings ADD COLUMN name VARCHAR(255) NOT NULL ;
ALTER TABLE pickings ADD COLUMN postal_code VARCHAR(10);
ALTER TABLE pickings ADD COLUMN city VARCHAR(255);
ALTER TABLE pickings ADD COLUMN email VARCHAR(255);
ALTER TABLE pickings ADD COLUMN phone VARCHAR(50);
ALTER TABLE pickings ALTER COLUMN producer_id DROP NOT NULL;