spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/cueillette_db
spring.datasource.username=postgres
spring.datasource.password=pgpicking
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=your-super-secret-key-change-this-in-production-must-be-long
jwt.expiration=86400000