package com.cueillette.backend.model;

public enum Label {
    AB,
    BIO_EUROPEEN,
    DEMETER,
    NATURE_ET_PROGRES,
    BIO_COHERENCE,
    HVE_NIVEAU_1,
    HVE_NIVEAU_2,
    HVE_NIVEAU_3,
    BEE_FRIENDLY,
    ZERO_RESIDU_PESTICIDES,
    VERGERS_ECORESPONSABLES,
    BIENVENUE_A_LA_FERME,
    PRODUCTEURS_FERMIERS,
    PRODUIT_EN_BRETAGNE,
    AGRI_ETHIQUE,
    FAIR_FOR_LIFE,
    BIOPARTENAIRE,
    GLOBAL_GAP,
    RAINFOREST_ALLIANCE,
    CONVERSION_BIO
}
